apiVersion: app/V1
kind: Deployment
metadata:
  name: deploy1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: label1
  template:
    metadata:
      labels:
        app: label1
    spec:
      container:
      - name: 
        image:
        port:
        - containerport: 80

